// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package comm;

public final class ProtocolMessage {
  private ProtocolMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .comm.Message.MessageType type = 1;
    /**
     * <code>required .comm.Message.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .comm.Message.MessageType type = 1;</code>
     */
    comm.ProtocolMessage.Message.MessageType getType();

    // optional string nodeId = 2;
    /**
     * <code>optional string nodeId = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>optional string nodeId = 2;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>optional string nodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    // optional string session = 3;
    /**
     * <code>optional string session = 3;</code>
     */
    boolean hasSession();
    /**
     * <code>optional string session = 3;</code>
     */
    java.lang.String getSession();
    /**
     * <code>optional string session = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    // optional int32 execution = 4;
    /**
     * <code>optional int32 execution = 4;</code>
     */
    boolean hasExecution();
    /**
     * <code>optional int32 execution = 4;</code>
     */
    int getExecution();

    // optional int32 totalNumberOfExecutions = 5;
    /**
     * <code>optional int32 totalNumberOfExecutions = 5;</code>
     */
    boolean hasTotalNumberOfExecutions();
    /**
     * <code>optional int32 totalNumberOfExecutions = 5;</code>
     */
    int getTotalNumberOfExecutions();

    // optional int32 round = 6;
    /**
     * <code>optional int32 round = 6;</code>
     */
    boolean hasRound();
    /**
     * <code>optional int32 round = 6;</code>
     */
    int getRound();

    // optional double val = 7;
    /**
     * <code>optional double val = 7;</code>
     */
    boolean hasVal();
    /**
     * <code>optional double val = 7;</code>
     */
    double getVal();

    // repeated double eigenvals = 8 [packed = true];
    /**
     * <code>repeated double eigenvals = 8 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getEigenvalsList();
    /**
     * <code>repeated double eigenvals = 8 [packed = true];</code>
     */
    int getEigenvalsCount();
    /**
     * <code>repeated double eigenvals = 8 [packed = true];</code>
     */
    double getEigenvals(int index);
  }
  /**
   * Protobuf type {@code comm.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              comm.ProtocolMessage.Message.MessageType value = comm.ProtocolMessage.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nodeId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              session_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              execution_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              totalNumberOfExecutions_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              round_ = input.readInt32();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              val_ = input.readDouble();
              break;
            }
            case 65: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                eigenvals_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000080;
              }
              eigenvals_.add(input.readDouble());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
                eigenvals_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000080;
              }
              while (input.getBytesUntilLimit() > 0) {
                eigenvals_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          eigenvals_ = java.util.Collections.unmodifiableList(eigenvals_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.ProtocolMessage.internal_static_comm_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.ProtocolMessage.internal_static_comm_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.ProtocolMessage.Message.class, comm.ProtocolMessage.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code comm.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NEW = 0;</code>
       */
      NEW(0, 0),
      /**
       * <code>INIT = 1;</code>
       */
      INIT(1, 1),
      /**
       * <code>NEXT = 2;</code>
       */
      NEXT(2, 2),
      /**
       * <code>GOSSIP = 3;</code>
       */
      GOSSIP(3, 3),
      /**
       * <code>LIVENESS_CHECK = 4;</code>
       */
      LIVENESS_CHECK(4, 4),
      ;

      /**
       * <code>NEW = 0;</code>
       */
      public static final int NEW_VALUE = 0;
      /**
       * <code>INIT = 1;</code>
       */
      public static final int INIT_VALUE = 1;
      /**
       * <code>NEXT = 2;</code>
       */
      public static final int NEXT_VALUE = 2;
      /**
       * <code>GOSSIP = 3;</code>
       */
      public static final int GOSSIP_VALUE = 3;
      /**
       * <code>LIVENESS_CHECK = 4;</code>
       */
      public static final int LIVENESS_CHECK_VALUE = 4;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return NEW;
          case 1: return INIT;
          case 2: return NEXT;
          case 3: return GOSSIP;
          case 4: return LIVENESS_CHECK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return comm.ProtocolMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:comm.Message.MessageType)
    }

    private int bitField0_;
    // required .comm.Message.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private comm.ProtocolMessage.Message.MessageType type_;
    /**
     * <code>required .comm.Message.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .comm.Message.MessageType type = 1;</code>
     */
    public comm.ProtocolMessage.Message.MessageType getType() {
      return type_;
    }

    // optional string nodeId = 2;
    public static final int NODEID_FIELD_NUMBER = 2;
    private java.lang.Object nodeId_;
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string session = 3;
    public static final int SESSION_FIELD_NUMBER = 3;
    private java.lang.Object session_;
    /**
     * <code>optional string session = 3;</code>
     */
    public boolean hasSession() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string session = 3;</code>
     */
    public java.lang.String getSession() {
      java.lang.Object ref = session_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          session_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string session = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      java.lang.Object ref = session_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 execution = 4;
    public static final int EXECUTION_FIELD_NUMBER = 4;
    private int execution_;
    /**
     * <code>optional int32 execution = 4;</code>
     */
    public boolean hasExecution() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 execution = 4;</code>
     */
    public int getExecution() {
      return execution_;
    }

    // optional int32 totalNumberOfExecutions = 5;
    public static final int TOTALNUMBEROFEXECUTIONS_FIELD_NUMBER = 5;
    private int totalNumberOfExecutions_;
    /**
     * <code>optional int32 totalNumberOfExecutions = 5;</code>
     */
    public boolean hasTotalNumberOfExecutions() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 totalNumberOfExecutions = 5;</code>
     */
    public int getTotalNumberOfExecutions() {
      return totalNumberOfExecutions_;
    }

    // optional int32 round = 6;
    public static final int ROUND_FIELD_NUMBER = 6;
    private int round_;
    /**
     * <code>optional int32 round = 6;</code>
     */
    public boolean hasRound() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 round = 6;</code>
     */
    public int getRound() {
      return round_;
    }

    // optional double val = 7;
    public static final int VAL_FIELD_NUMBER = 7;
    private double val_;
    /**
     * <code>optional double val = 7;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double val = 7;</code>
     */
    public double getVal() {
      return val_;
    }

    // repeated double eigenvals = 8 [packed = true];
    public static final int EIGENVALS_FIELD_NUMBER = 8;
    private java.util.List<java.lang.Double> eigenvals_;
    /**
     * <code>repeated double eigenvals = 8 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getEigenvalsList() {
      return eigenvals_;
    }
    /**
     * <code>repeated double eigenvals = 8 [packed = true];</code>
     */
    public int getEigenvalsCount() {
      return eigenvals_.size();
    }
    /**
     * <code>repeated double eigenvals = 8 [packed = true];</code>
     */
    public double getEigenvals(int index) {
      return eigenvals_.get(index);
    }
    private int eigenvalsMemoizedSerializedSize = -1;

    private void initFields() {
      type_ = comm.ProtocolMessage.Message.MessageType.NEW;
      nodeId_ = "";
      session_ = "";
      execution_ = 0;
      totalNumberOfExecutions_ = 0;
      round_ = 0;
      val_ = 0D;
      eigenvals_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, execution_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, totalNumberOfExecutions_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, round_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, val_);
      }
      if (getEigenvalsList().size() > 0) {
        output.writeRawVarint32(66);
        output.writeRawVarint32(eigenvalsMemoizedSerializedSize);
      }
      for (int i = 0; i < eigenvals_.size(); i++) {
        output.writeDoubleNoTag(eigenvals_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, execution_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, totalNumberOfExecutions_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, round_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, val_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getEigenvalsList().size();
        size += dataSize;
        if (!getEigenvalsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        eigenvalsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static comm.ProtocolMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.ProtocolMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.ProtocolMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.ProtocolMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.ProtocolMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.ProtocolMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static comm.ProtocolMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static comm.ProtocolMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static comm.ProtocolMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.ProtocolMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(comm.ProtocolMessage.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comm.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements comm.ProtocolMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.ProtocolMessage.internal_static_comm_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.ProtocolMessage.internal_static_comm_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.ProtocolMessage.Message.class, comm.ProtocolMessage.Message.Builder.class);
      }

      // Construct using comm.ProtocolMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = comm.ProtocolMessage.Message.MessageType.NEW;
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        session_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        execution_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        totalNumberOfExecutions_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        round_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        val_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        eigenvals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.ProtocolMessage.internal_static_comm_Message_descriptor;
      }

      public comm.ProtocolMessage.Message getDefaultInstanceForType() {
        return comm.ProtocolMessage.Message.getDefaultInstance();
      }

      public comm.ProtocolMessage.Message build() {
        comm.ProtocolMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public comm.ProtocolMessage.Message buildPartial() {
        comm.ProtocolMessage.Message result = new comm.ProtocolMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.session_ = session_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.execution_ = execution_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.totalNumberOfExecutions_ = totalNumberOfExecutions_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.round_ = round_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.val_ = val_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          eigenvals_ = java.util.Collections.unmodifiableList(eigenvals_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.eigenvals_ = eigenvals_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.ProtocolMessage.Message) {
          return mergeFrom((comm.ProtocolMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.ProtocolMessage.Message other) {
        if (other == comm.ProtocolMessage.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasNodeId()) {
          bitField0_ |= 0x00000002;
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (other.hasSession()) {
          bitField0_ |= 0x00000004;
          session_ = other.session_;
          onChanged();
        }
        if (other.hasExecution()) {
          setExecution(other.getExecution());
        }
        if (other.hasTotalNumberOfExecutions()) {
          setTotalNumberOfExecutions(other.getTotalNumberOfExecutions());
        }
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        if (!other.eigenvals_.isEmpty()) {
          if (eigenvals_.isEmpty()) {
            eigenvals_ = other.eigenvals_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureEigenvalsIsMutable();
            eigenvals_.addAll(other.eigenvals_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comm.ProtocolMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comm.ProtocolMessage.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .comm.Message.MessageType type = 1;
      private comm.ProtocolMessage.Message.MessageType type_ = comm.ProtocolMessage.Message.MessageType.NEW;
      /**
       * <code>required .comm.Message.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .comm.Message.MessageType type = 1;</code>
       */
      public comm.ProtocolMessage.Message.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .comm.Message.MessageType type = 1;</code>
       */
      public Builder setType(comm.ProtocolMessage.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .comm.Message.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = comm.ProtocolMessage.Message.MessageType.NEW;
        onChanged();
        return this;
      }

      // optional string nodeId = 2;
      private java.lang.Object nodeId_ = "";
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }

      // optional string session = 3;
      private java.lang.Object session_ = "";
      /**
       * <code>optional string session = 3;</code>
       */
      public boolean hasSession() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string session = 3;</code>
       */
      public java.lang.String getSession() {
        java.lang.Object ref = session_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string session = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        java.lang.Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session = 3;</code>
       */
      public Builder setSession(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 3;</code>
       */
      public Builder clearSession() {
        bitField0_ = (bitField0_ & ~0x00000004);
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 3;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        session_ = value;
        onChanged();
        return this;
      }

      // optional int32 execution = 4;
      private int execution_ ;
      /**
       * <code>optional int32 execution = 4;</code>
       */
      public boolean hasExecution() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 execution = 4;</code>
       */
      public int getExecution() {
        return execution_;
      }
      /**
       * <code>optional int32 execution = 4;</code>
       */
      public Builder setExecution(int value) {
        bitField0_ |= 0x00000008;
        execution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 execution = 4;</code>
       */
      public Builder clearExecution() {
        bitField0_ = (bitField0_ & ~0x00000008);
        execution_ = 0;
        onChanged();
        return this;
      }

      // optional int32 totalNumberOfExecutions = 5;
      private int totalNumberOfExecutions_ ;
      /**
       * <code>optional int32 totalNumberOfExecutions = 5;</code>
       */
      public boolean hasTotalNumberOfExecutions() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 totalNumberOfExecutions = 5;</code>
       */
      public int getTotalNumberOfExecutions() {
        return totalNumberOfExecutions_;
      }
      /**
       * <code>optional int32 totalNumberOfExecutions = 5;</code>
       */
      public Builder setTotalNumberOfExecutions(int value) {
        bitField0_ |= 0x00000010;
        totalNumberOfExecutions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalNumberOfExecutions = 5;</code>
       */
      public Builder clearTotalNumberOfExecutions() {
        bitField0_ = (bitField0_ & ~0x00000010);
        totalNumberOfExecutions_ = 0;
        onChanged();
        return this;
      }

      // optional int32 round = 6;
      private int round_ ;
      /**
       * <code>optional int32 round = 6;</code>
       */
      public boolean hasRound() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 round = 6;</code>
       */
      public int getRound() {
        return round_;
      }
      /**
       * <code>optional int32 round = 6;</code>
       */
      public Builder setRound(int value) {
        bitField0_ |= 0x00000020;
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 round = 6;</code>
       */
      public Builder clearRound() {
        bitField0_ = (bitField0_ & ~0x00000020);
        round_ = 0;
        onChanged();
        return this;
      }

      // optional double val = 7;
      private double val_ ;
      /**
       * <code>optional double val = 7;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double val = 7;</code>
       */
      public double getVal() {
        return val_;
      }
      /**
       * <code>optional double val = 7;</code>
       */
      public Builder setVal(double value) {
        bitField0_ |= 0x00000040;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double val = 7;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000040);
        val_ = 0D;
        onChanged();
        return this;
      }

      // repeated double eigenvals = 8 [packed = true];
      private java.util.List<java.lang.Double> eigenvals_ = java.util.Collections.emptyList();
      private void ensureEigenvalsIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          eigenvals_ = new java.util.ArrayList<java.lang.Double>(eigenvals_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getEigenvalsList() {
        return java.util.Collections.unmodifiableList(eigenvals_);
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public int getEigenvalsCount() {
        return eigenvals_.size();
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public double getEigenvals(int index) {
        return eigenvals_.get(index);
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public Builder setEigenvals(
          int index, double value) {
        ensureEigenvalsIsMutable();
        eigenvals_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public Builder addEigenvals(double value) {
        ensureEigenvalsIsMutable();
        eigenvals_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public Builder addAllEigenvals(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureEigenvalsIsMutable();
        super.addAll(values, eigenvals_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double eigenvals = 8 [packed = true];</code>
       */
      public Builder clearEigenvals() {
        eigenvals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:comm.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:comm.Message)
  }

  public interface SessionEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .comm.SessionEvent.EventType type = 1;
    /**
     * <code>required .comm.SessionEvent.EventType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .comm.SessionEvent.EventType type = 1;</code>
     */
    comm.ProtocolMessage.SessionEvent.EventType getType();

    // required string localNodeId = 2;
    /**
     * <code>required string localNodeId = 2;</code>
     */
    boolean hasLocalNodeId();
    /**
     * <code>required string localNodeId = 2;</code>
     */
    java.lang.String getLocalNodeId();
    /**
     * <code>required string localNodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocalNodeIdBytes();

    // required string sessionId = 3;
    /**
     * <code>required string sessionId = 3;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required string sessionId = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>required string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // required int64 date = 4;
    /**
     * <code>required int64 date = 4;</code>
     */
    boolean hasDate();
    /**
     * <code>required int64 date = 4;</code>
     */
    long getDate();

    // repeated double eigenvalues = 5;
    /**
     * <code>repeated double eigenvalues = 5;</code>
     */
    java.util.List<java.lang.Double> getEigenvaluesList();
    /**
     * <code>repeated double eigenvalues = 5;</code>
     */
    int getEigenvaluesCount();
    /**
     * <code>repeated double eigenvalues = 5;</code>
     */
    double getEigenvalues(int index);

    // repeated string outNeighbors = 6;
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    java.util.List<java.lang.String>
    getOutNeighborsList();
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    int getOutNeighborsCount();
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    java.lang.String getOutNeighbors(int index);
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    com.google.protobuf.ByteString
        getOutNeighborsBytes(int index);
  }
  /**
   * Protobuf type {@code comm.SessionEvent}
   */
  public static final class SessionEvent extends
      com.google.protobuf.GeneratedMessage
      implements SessionEventOrBuilder {
    // Use SessionEvent.newBuilder() to construct.
    private SessionEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SessionEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SessionEvent defaultInstance;
    public static SessionEvent getDefaultInstance() {
      return defaultInstance;
    }

    public SessionEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SessionEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              comm.ProtocolMessage.SessionEvent.EventType value = comm.ProtocolMessage.SessionEvent.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              localNodeId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              date_ = input.readInt64();
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                eigenvalues_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              eigenvalues_.add(input.readDouble());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                eigenvalues_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                eigenvalues_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                outNeighbors_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              outNeighbors_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          eigenvalues_ = java.util.Collections.unmodifiableList(eigenvalues_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          outNeighbors_ = new com.google.protobuf.UnmodifiableLazyStringList(outNeighbors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.ProtocolMessage.internal_static_comm_SessionEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.ProtocolMessage.internal_static_comm_SessionEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.ProtocolMessage.SessionEvent.class, comm.ProtocolMessage.SessionEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<SessionEvent> PARSER =
        new com.google.protobuf.AbstractParser<SessionEvent>() {
      public SessionEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SessionEvent> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code comm.SessionEvent.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INITIAL = 0;</code>
       */
      INITIAL(0, 0),
      /**
       * <code>TERMINAL = 1;</code>
       */
      TERMINAL(1, 1),
      ;

      /**
       * <code>INITIAL = 0;</code>
       */
      public static final int INITIAL_VALUE = 0;
      /**
       * <code>TERMINAL = 1;</code>
       */
      public static final int TERMINAL_VALUE = 1;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return INITIAL;
          case 1: return TERMINAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return comm.ProtocolMessage.SessionEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:comm.SessionEvent.EventType)
    }

    private int bitField0_;
    // required .comm.SessionEvent.EventType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private comm.ProtocolMessage.SessionEvent.EventType type_;
    /**
     * <code>required .comm.SessionEvent.EventType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .comm.SessionEvent.EventType type = 1;</code>
     */
    public comm.ProtocolMessage.SessionEvent.EventType getType() {
      return type_;
    }

    // required string localNodeId = 2;
    public static final int LOCALNODEID_FIELD_NUMBER = 2;
    private java.lang.Object localNodeId_;
    /**
     * <code>required string localNodeId = 2;</code>
     */
    public boolean hasLocalNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string localNodeId = 2;</code>
     */
    public java.lang.String getLocalNodeId() {
      java.lang.Object ref = localNodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localNodeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string localNodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocalNodeIdBytes() {
      java.lang.Object ref = localNodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string sessionId = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private java.lang.Object sessionId_;
    /**
     * <code>required string sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 date = 4;
    public static final int DATE_FIELD_NUMBER = 4;
    private long date_;
    /**
     * <code>required int64 date = 4;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 date = 4;</code>
     */
    public long getDate() {
      return date_;
    }

    // repeated double eigenvalues = 5;
    public static final int EIGENVALUES_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Double> eigenvalues_;
    /**
     * <code>repeated double eigenvalues = 5;</code>
     */
    public java.util.List<java.lang.Double>
        getEigenvaluesList() {
      return eigenvalues_;
    }
    /**
     * <code>repeated double eigenvalues = 5;</code>
     */
    public int getEigenvaluesCount() {
      return eigenvalues_.size();
    }
    /**
     * <code>repeated double eigenvalues = 5;</code>
     */
    public double getEigenvalues(int index) {
      return eigenvalues_.get(index);
    }

    // repeated string outNeighbors = 6;
    public static final int OUTNEIGHBORS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList outNeighbors_;
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    public java.util.List<java.lang.String>
        getOutNeighborsList() {
      return outNeighbors_;
    }
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    public int getOutNeighborsCount() {
      return outNeighbors_.size();
    }
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    public java.lang.String getOutNeighbors(int index) {
      return outNeighbors_.get(index);
    }
    /**
     * <code>repeated string outNeighbors = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOutNeighborsBytes(int index) {
      return outNeighbors_.getByteString(index);
    }

    private void initFields() {
      type_ = comm.ProtocolMessage.SessionEvent.EventType.INITIAL;
      localNodeId_ = "";
      sessionId_ = "";
      date_ = 0L;
      eigenvalues_ = java.util.Collections.emptyList();
      outNeighbors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLocalNodeIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, date_);
      }
      for (int i = 0; i < eigenvalues_.size(); i++) {
        output.writeDouble(5, eigenvalues_.get(i));
      }
      for (int i = 0; i < outNeighbors_.size(); i++) {
        output.writeBytes(6, outNeighbors_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLocalNodeIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, date_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getEigenvaluesList().size();
        size += dataSize;
        size += 1 * getEigenvaluesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < outNeighbors_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(outNeighbors_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getOutNeighborsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static comm.ProtocolMessage.SessionEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static comm.ProtocolMessage.SessionEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static comm.ProtocolMessage.SessionEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.ProtocolMessage.SessionEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(comm.ProtocolMessage.SessionEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comm.SessionEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements comm.ProtocolMessage.SessionEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.ProtocolMessage.internal_static_comm_SessionEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.ProtocolMessage.internal_static_comm_SessionEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.ProtocolMessage.SessionEvent.class, comm.ProtocolMessage.SessionEvent.Builder.class);
      }

      // Construct using comm.ProtocolMessage.SessionEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = comm.ProtocolMessage.SessionEvent.EventType.INITIAL;
        bitField0_ = (bitField0_ & ~0x00000001);
        localNodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        eigenvalues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        outNeighbors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.ProtocolMessage.internal_static_comm_SessionEvent_descriptor;
      }

      public comm.ProtocolMessage.SessionEvent getDefaultInstanceForType() {
        return comm.ProtocolMessage.SessionEvent.getDefaultInstance();
      }

      public comm.ProtocolMessage.SessionEvent build() {
        comm.ProtocolMessage.SessionEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public comm.ProtocolMessage.SessionEvent buildPartial() {
        comm.ProtocolMessage.SessionEvent result = new comm.ProtocolMessage.SessionEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localNodeId_ = localNodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          eigenvalues_ = java.util.Collections.unmodifiableList(eigenvalues_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.eigenvalues_ = eigenvalues_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          outNeighbors_ = new com.google.protobuf.UnmodifiableLazyStringList(
              outNeighbors_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.outNeighbors_ = outNeighbors_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.ProtocolMessage.SessionEvent) {
          return mergeFrom((comm.ProtocolMessage.SessionEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.ProtocolMessage.SessionEvent other) {
        if (other == comm.ProtocolMessage.SessionEvent.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLocalNodeId()) {
          bitField0_ |= 0x00000002;
          localNodeId_ = other.localNodeId_;
          onChanged();
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000004;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (!other.eigenvalues_.isEmpty()) {
          if (eigenvalues_.isEmpty()) {
            eigenvalues_ = other.eigenvalues_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureEigenvaluesIsMutable();
            eigenvalues_.addAll(other.eigenvalues_);
          }
          onChanged();
        }
        if (!other.outNeighbors_.isEmpty()) {
          if (outNeighbors_.isEmpty()) {
            outNeighbors_ = other.outNeighbors_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureOutNeighborsIsMutable();
            outNeighbors_.addAll(other.outNeighbors_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasLocalNodeId()) {
          
          return false;
        }
        if (!hasSessionId()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comm.ProtocolMessage.SessionEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comm.ProtocolMessage.SessionEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .comm.SessionEvent.EventType type = 1;
      private comm.ProtocolMessage.SessionEvent.EventType type_ = comm.ProtocolMessage.SessionEvent.EventType.INITIAL;
      /**
       * <code>required .comm.SessionEvent.EventType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .comm.SessionEvent.EventType type = 1;</code>
       */
      public comm.ProtocolMessage.SessionEvent.EventType getType() {
        return type_;
      }
      /**
       * <code>required .comm.SessionEvent.EventType type = 1;</code>
       */
      public Builder setType(comm.ProtocolMessage.SessionEvent.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .comm.SessionEvent.EventType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = comm.ProtocolMessage.SessionEvent.EventType.INITIAL;
        onChanged();
        return this;
      }

      // required string localNodeId = 2;
      private java.lang.Object localNodeId_ = "";
      /**
       * <code>required string localNodeId = 2;</code>
       */
      public boolean hasLocalNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string localNodeId = 2;</code>
       */
      public java.lang.String getLocalNodeId() {
        java.lang.Object ref = localNodeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localNodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string localNodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocalNodeIdBytes() {
        java.lang.Object ref = localNodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localNodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string localNodeId = 2;</code>
       */
      public Builder setLocalNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localNodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string localNodeId = 2;</code>
       */
      public Builder clearLocalNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localNodeId_ = getDefaultInstance().getLocalNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>required string localNodeId = 2;</code>
       */
      public Builder setLocalNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localNodeId_ = value;
        onChanged();
        return this;
      }

      // required string sessionId = 3;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>required string sessionId = 3;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // required int64 date = 4;
      private long date_ ;
      /**
       * <code>required int64 date = 4;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 date = 4;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>required int64 date = 4;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 date = 4;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = 0L;
        onChanged();
        return this;
      }

      // repeated double eigenvalues = 5;
      private java.util.List<java.lang.Double> eigenvalues_ = java.util.Collections.emptyList();
      private void ensureEigenvaluesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          eigenvalues_ = new java.util.ArrayList<java.lang.Double>(eigenvalues_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public java.util.List<java.lang.Double>
          getEigenvaluesList() {
        return java.util.Collections.unmodifiableList(eigenvalues_);
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public int getEigenvaluesCount() {
        return eigenvalues_.size();
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public double getEigenvalues(int index) {
        return eigenvalues_.get(index);
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public Builder setEigenvalues(
          int index, double value) {
        ensureEigenvaluesIsMutable();
        eigenvalues_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public Builder addEigenvalues(double value) {
        ensureEigenvaluesIsMutable();
        eigenvalues_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public Builder addAllEigenvalues(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureEigenvaluesIsMutable();
        super.addAll(values, eigenvalues_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double eigenvalues = 5;</code>
       */
      public Builder clearEigenvalues() {
        eigenvalues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // repeated string outNeighbors = 6;
      private com.google.protobuf.LazyStringList outNeighbors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOutNeighborsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          outNeighbors_ = new com.google.protobuf.LazyStringArrayList(outNeighbors_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public java.util.List<java.lang.String>
          getOutNeighborsList() {
        return java.util.Collections.unmodifiableList(outNeighbors_);
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public int getOutNeighborsCount() {
        return outNeighbors_.size();
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public java.lang.String getOutNeighbors(int index) {
        return outNeighbors_.get(index);
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOutNeighborsBytes(int index) {
        return outNeighbors_.getByteString(index);
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public Builder setOutNeighbors(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutNeighborsIsMutable();
        outNeighbors_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public Builder addOutNeighbors(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutNeighborsIsMutable();
        outNeighbors_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public Builder addAllOutNeighbors(
          java.lang.Iterable<java.lang.String> values) {
        ensureOutNeighborsIsMutable();
        super.addAll(values, outNeighbors_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public Builder clearOutNeighbors() {
        outNeighbors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string outNeighbors = 6;</code>
       */
      public Builder addOutNeighborsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutNeighborsIsMutable();
        outNeighbors_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:comm.SessionEvent)
    }

    static {
      defaultInstance = new SessionEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:comm.SessionEvent)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_comm_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_comm_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_comm_SessionEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_comm_SessionEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/resources/message.proto\022\004comm" +
      "\"\206\002\n\007Message\022\'\n\004type\030\001 \002(\0162\031.comm.Messag" +
      "e.MessageType\022\016\n\006nodeId\030\002 \001(\t\022\017\n\007session" +
      "\030\003 \001(\t\022\021\n\texecution\030\004 \001(\005\022\037\n\027totalNumber" +
      "OfExecutions\030\005 \001(\005\022\r\n\005round\030\006 \001(\005\022\013\n\003val" +
      "\030\007 \001(\001\022\025\n\teigenvals\030\010 \003(\001B\002\020\001\"J\n\013Message" +
      "Type\022\007\n\003NEW\020\000\022\010\n\004INIT\020\001\022\010\n\004NEXT\020\002\022\n\n\006GOS" +
      "SIP\020\003\022\022\n\016LIVENESS_CHECK\020\004\"\303\001\n\014SessionEve" +
      "nt\022*\n\004type\030\001 \002(\0162\034.comm.SessionEvent.Eve" +
      "ntType\022\023\n\013localNodeId\030\002 \002(\t\022\021\n\tsessionId",
      "\030\003 \002(\t\022\014\n\004date\030\004 \002(\003\022\023\n\013eigenvalues\030\005 \003(" +
      "\001\022\024\n\014outNeighbors\030\006 \003(\t\"&\n\tEventType\022\013\n\007" +
      "INITIAL\020\000\022\014\n\010TERMINAL\020\001B\027\n\004commB\017Protoco" +
      "lMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_comm_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_comm_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_comm_Message_descriptor,
              new java.lang.String[] { "Type", "NodeId", "Session", "Execution", "TotalNumberOfExecutions", "Round", "Val", "Eigenvals", });
          internal_static_comm_SessionEvent_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_comm_SessionEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_comm_SessionEvent_descriptor,
              new java.lang.String[] { "Type", "LocalNodeId", "SessionId", "Date", "Eigenvalues", "OutNeighbors", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
