// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appMessage.proto

package app;

public final class ApplicationMessage {
  private ApplicationMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .app.AppMessage.MessageType type = 1;
    /**
     * <code>required .app.AppMessage.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .app.AppMessage.MessageType type = 1;</code>
     */
    app.ApplicationMessage.AppMessage.MessageType getType();

    // required string queryId = 2;
    /**
     * <code>required string queryId = 2;</code>
     */
    boolean hasQueryId();
    /**
     * <code>required string queryId = 2;</code>
     */
    java.lang.String getQueryId();
    /**
     * <code>required string queryId = 2;</code>
     */
    com.google.protobuf.ByteString
        getQueryIdBytes();

    // optional double mixTime = 3;
    /**
     * <code>optional double mixTime = 3;</code>
     */
    boolean hasMixTime();
    /**
     * <code>optional double mixTime = 3;</code>
     */
    double getMixTime();

    // optional int32 round = 4;
    /**
     * <code>optional int32 round = 4;</code>
     */
    boolean hasRound();
    /**
     * <code>optional int32 round = 4;</code>
     */
    int getRound();

    // optional double weight = 5;
    /**
     * <code>optional double weight = 5;</code>
     */
    boolean hasWeight();
    /**
     * <code>optional double weight = 5;</code>
     */
    double getWeight();

    // optional double value = 6;
    /**
     * <code>optional double value = 6;</code>
     */
    boolean hasValue();
    /**
     * <code>optional double value = 6;</code>
     */
    double getValue();
  }
  /**
   * Protobuf type {@code app.AppMessage}
   */
  public static final class AppMessage extends
      com.google.protobuf.GeneratedMessage
      implements AppMessageOrBuilder {
    // Use AppMessage.newBuilder() to construct.
    private AppMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppMessage defaultInstance;
    public static AppMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AppMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              app.ApplicationMessage.AppMessage.MessageType value = app.ApplicationMessage.AppMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              queryId_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              mixTime_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              round_ = input.readInt32();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              weight_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              value_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.ApplicationMessage.internal_static_app_AppMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.ApplicationMessage.internal_static_app_AppMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.ApplicationMessage.AppMessage.class, app.ApplicationMessage.AppMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<AppMessage> PARSER =
        new com.google.protobuf.AbstractParser<AppMessage>() {
      public AppMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code app.AppMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NEW = 0;</code>
       */
      NEW(0, 0),
      /**
       * <code>VAL = 1;</code>
       */
      VAL(1, 1),
      /**
       * <code>VOID = 2;</code>
       */
      VOID(2, 2),
      /**
       * <code>REAL_VAL = 3;</code>
       */
      REAL_VAL(3, 3),
      ;

      /**
       * <code>NEW = 0;</code>
       */
      public static final int NEW_VALUE = 0;
      /**
       * <code>VAL = 1;</code>
       */
      public static final int VAL_VALUE = 1;
      /**
       * <code>VOID = 2;</code>
       */
      public static final int VOID_VALUE = 2;
      /**
       * <code>REAL_VAL = 3;</code>
       */
      public static final int REAL_VAL_VALUE = 3;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return NEW;
          case 1: return VAL;
          case 2: return VOID;
          case 3: return REAL_VAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return app.ApplicationMessage.AppMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:app.AppMessage.MessageType)
    }

    private int bitField0_;
    // required .app.AppMessage.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private app.ApplicationMessage.AppMessage.MessageType type_;
    /**
     * <code>required .app.AppMessage.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .app.AppMessage.MessageType type = 1;</code>
     */
    public app.ApplicationMessage.AppMessage.MessageType getType() {
      return type_;
    }

    // required string queryId = 2;
    public static final int QUERYID_FIELD_NUMBER = 2;
    private java.lang.Object queryId_;
    /**
     * <code>required string queryId = 2;</code>
     */
    public boolean hasQueryId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string queryId = 2;</code>
     */
    public java.lang.String getQueryId() {
      java.lang.Object ref = queryId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          queryId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string queryId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQueryIdBytes() {
      java.lang.Object ref = queryId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double mixTime = 3;
    public static final int MIXTIME_FIELD_NUMBER = 3;
    private double mixTime_;
    /**
     * <code>optional double mixTime = 3;</code>
     */
    public boolean hasMixTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double mixTime = 3;</code>
     */
    public double getMixTime() {
      return mixTime_;
    }

    // optional int32 round = 4;
    public static final int ROUND_FIELD_NUMBER = 4;
    private int round_;
    /**
     * <code>optional int32 round = 4;</code>
     */
    public boolean hasRound() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 round = 4;</code>
     */
    public int getRound() {
      return round_;
    }

    // optional double weight = 5;
    public static final int WEIGHT_FIELD_NUMBER = 5;
    private double weight_;
    /**
     * <code>optional double weight = 5;</code>
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double weight = 5;</code>
     */
    public double getWeight() {
      return weight_;
    }

    // optional double value = 6;
    public static final int VALUE_FIELD_NUMBER = 6;
    private double value_;
    /**
     * <code>optional double value = 6;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double value = 6;</code>
     */
    public double getValue() {
      return value_;
    }

    private void initFields() {
      type_ = app.ApplicationMessage.AppMessage.MessageType.NEW;
      queryId_ = "";
      mixTime_ = 0D;
      round_ = 0;
      weight_ = 0D;
      value_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueryId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getQueryIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, mixTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, round_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, weight_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getQueryIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, mixTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, round_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, weight_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.ApplicationMessage.AppMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.ApplicationMessage.AppMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.ApplicationMessage.AppMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.ApplicationMessage.AppMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.ApplicationMessage.AppMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code app.AppMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements app.ApplicationMessage.AppMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.ApplicationMessage.internal_static_app_AppMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.ApplicationMessage.internal_static_app_AppMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.ApplicationMessage.AppMessage.class, app.ApplicationMessage.AppMessage.Builder.class);
      }

      // Construct using app.ApplicationMessage.AppMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = app.ApplicationMessage.AppMessage.MessageType.NEW;
        bitField0_ = (bitField0_ & ~0x00000001);
        queryId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mixTime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        round_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        weight_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.ApplicationMessage.internal_static_app_AppMessage_descriptor;
      }

      public app.ApplicationMessage.AppMessage getDefaultInstanceForType() {
        return app.ApplicationMessage.AppMessage.getDefaultInstance();
      }

      public app.ApplicationMessage.AppMessage build() {
        app.ApplicationMessage.AppMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.ApplicationMessage.AppMessage buildPartial() {
        app.ApplicationMessage.AppMessage result = new app.ApplicationMessage.AppMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.queryId_ = queryId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mixTime_ = mixTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.round_ = round_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.weight_ = weight_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.ApplicationMessage.AppMessage) {
          return mergeFrom((app.ApplicationMessage.AppMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.ApplicationMessage.AppMessage other) {
        if (other == app.ApplicationMessage.AppMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasQueryId()) {
          bitField0_ |= 0x00000002;
          queryId_ = other.queryId_;
          onChanged();
        }
        if (other.hasMixTime()) {
          setMixTime(other.getMixTime());
        }
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasQueryId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.ApplicationMessage.AppMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.ApplicationMessage.AppMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .app.AppMessage.MessageType type = 1;
      private app.ApplicationMessage.AppMessage.MessageType type_ = app.ApplicationMessage.AppMessage.MessageType.NEW;
      /**
       * <code>required .app.AppMessage.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .app.AppMessage.MessageType type = 1;</code>
       */
      public app.ApplicationMessage.AppMessage.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .app.AppMessage.MessageType type = 1;</code>
       */
      public Builder setType(app.ApplicationMessage.AppMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .app.AppMessage.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = app.ApplicationMessage.AppMessage.MessageType.NEW;
        onChanged();
        return this;
      }

      // required string queryId = 2;
      private java.lang.Object queryId_ = "";
      /**
       * <code>required string queryId = 2;</code>
       */
      public boolean hasQueryId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string queryId = 2;</code>
       */
      public java.lang.String getQueryId() {
        java.lang.Object ref = queryId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          queryId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string queryId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQueryIdBytes() {
        java.lang.Object ref = queryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string queryId = 2;</code>
       */
      public Builder setQueryId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        queryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string queryId = 2;</code>
       */
      public Builder clearQueryId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        queryId_ = getDefaultInstance().getQueryId();
        onChanged();
        return this;
      }
      /**
       * <code>required string queryId = 2;</code>
       */
      public Builder setQueryIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        queryId_ = value;
        onChanged();
        return this;
      }

      // optional double mixTime = 3;
      private double mixTime_ ;
      /**
       * <code>optional double mixTime = 3;</code>
       */
      public boolean hasMixTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double mixTime = 3;</code>
       */
      public double getMixTime() {
        return mixTime_;
      }
      /**
       * <code>optional double mixTime = 3;</code>
       */
      public Builder setMixTime(double value) {
        bitField0_ |= 0x00000004;
        mixTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double mixTime = 3;</code>
       */
      public Builder clearMixTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mixTime_ = 0D;
        onChanged();
        return this;
      }

      // optional int32 round = 4;
      private int round_ ;
      /**
       * <code>optional int32 round = 4;</code>
       */
      public boolean hasRound() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 round = 4;</code>
       */
      public int getRound() {
        return round_;
      }
      /**
       * <code>optional int32 round = 4;</code>
       */
      public Builder setRound(int value) {
        bitField0_ |= 0x00000008;
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 round = 4;</code>
       */
      public Builder clearRound() {
        bitField0_ = (bitField0_ & ~0x00000008);
        round_ = 0;
        onChanged();
        return this;
      }

      // optional double weight = 5;
      private double weight_ ;
      /**
       * <code>optional double weight = 5;</code>
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double weight = 5;</code>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>optional double weight = 5;</code>
       */
      public Builder setWeight(double value) {
        bitField0_ |= 0x00000010;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double weight = 5;</code>
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        weight_ = 0D;
        onChanged();
        return this;
      }

      // optional double value = 6;
      private double value_ ;
      /**
       * <code>optional double value = 6;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double value = 6;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 6;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000020;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double value = 6;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        value_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:app.AppMessage)
    }

    static {
      defaultInstance = new AppMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:app.AppMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_AppMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_AppMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020appMessage.proto\022\003app\"\300\001\n\nAppMessage\022)" +
      "\n\004type\030\001 \002(\0162\033.app.AppMessage.MessageTyp" +
      "e\022\017\n\007queryId\030\002 \002(\t\022\017\n\007mixTime\030\003 \001(\001\022\r\n\005r" +
      "ound\030\004 \001(\005\022\016\n\006weight\030\005 \001(\001\022\r\n\005value\030\006 \001(" +
      "\001\"7\n\013MessageType\022\007\n\003NEW\020\000\022\007\n\003VAL\020\001\022\010\n\004VO" +
      "ID\020\002\022\014\n\010REAL_VAL\020\003B\031\n\003appB\022ApplicationMe" +
      "ssage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_app_AppMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_app_AppMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_AppMessage_descriptor,
              new java.lang.String[] { "Type", "QueryId", "MixTime", "Round", "Weight", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
